### ISSUE TITLE
All configuration variables in EnvConfig must be set in your deployment environment

### ISSUE THREAD

**Issue by bwdmonkey** [bobheadxi/calories#22] opened 2017-11-12 14:39 UTC
I am getting the following error.

`All configuration variables in EnvConfig must be set in your deployment environment`

Can someone print their `heroku config`? I have FB_PAGE_ID, FB_TOKEN, HEROKU_URL.

**Comment by bobheadxi** [comment] 2017-11-12 16:17
Not really a ticket-worthy bug since I wrote that error message and _**this change isn't even merged yet**_ 😉 

This happens because you're on my PR branch `19-get-user`, where I added a config variable check (see description of #21 ) - you now need to set `DABATASE_URL` as well. Please make comments about PR improvements in the actual PR if the issue is PR-specific, since this does not affect `dev` or `master` yet💘 

I'll make the error message and README more descriptive though (see 72f5217). Also, I've added you as a tester to the Calories facebook page - you won't be able to deploy and there's no way to see who's branch is live, but it'll usually just be the latest PR and the bot will respond 😄

**Closed as completed by bobheadxi** 2017-11-12 16:17 UTC
Labels: bug
